### ISSUE TITLE
GEO - near seas, a margin needs to be used

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-core-services#2]
When a user is near a sea, the GPS location might be unreliable, placing the point in the sea, and therefore outside the boundary. Therefore, if a geolookup fails, we should try again with a distance of 1 km or so, to account for this.

**Comment by iperdomo** [comment]
It seems that other reverse geo search also _adjust_ to a near known point, e.g. This should be a sea between Utila island and La Ceiba (Honduras)
- http://nominatim.openstreetmap.org/reverse?format=json&lat=16.094861&lon=-86.904238

``` javascript
{
    "place_id": "54573824",
    "licence": "Data \u00a9 OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright",
    "osm_type": "way",
    "osm_id": "59677652",
    "lat": "16.097234",
    "lon": "-86.8953928",
    "display_name": "Main Street, El Centro, Utila Town, Honduras",
    "address": {
        "road": "Main Street",
        "suburb": "El Centro",
        "town": "Utila Town",
        "country": "Honduras",
        "country_code": "hn"
    }
}
```

**Comment by mtwestra** [comment]
Yes, the idea would be to do this:

1) try to find a point inside a geometry
2) if no luck, try to find a point that is in the neighbourhood of a geometry
3) if no luck, try to find out in which sea we are (it might be used on a ship)
mark
